### ISSUE TITLE
Inflections make cas_devise_authenticatable not compatible with CASino

### ISSUE THREAD

**Issue by tomascharad** [rbCAS/CASino#101]
Hi guys,

Some of your inflections declared as:

  ActiveSupport::Inflector.inflections do |inflect|
    inflect.acronym 'CAS' #This one specifically
    inflect.acronym 'CASino' 
  end

Are causing incompatibilities when using the devise strategy :cas_authenticatable

This causes that the methods in devise to_s.classify return CASAuthenticatable instead of CasAuthenticatable

**Comment by pencil** [comment]
I agree that inflections should not be used in an engine.

But why are you using CASino and Devise in the same project? Mixing CASino and Devise in the same project will lead to some other problems and is generally not recommended.

**Comment by tomascharad** [comment]
We wanted to have all of our user logic and administration in the same place. Given this, the administration end needed to be authenticable but this conflict made us to migrate the administration to another isolated app. Doing it was ok, but I guess that in the future there could be more people looking for the structure as we were.

**Comment by diegobernardes** [comment]
@pencil why u don't recommend running devise with casino? what kind of problems can happen?

its awful to have the user registration in one place and the login in another

**Comment by pencil** [comment]
> why u don't recommend running devise with casino?

Devise uses it's own logic to determine if a user is logged in or not. This can lead to inconsistent states (e.g. Devise thinks a user is signed in, CASino does not agree and vice versa)

> its awful to have the user registration in one place and the login in another

Why so? The only downside with having two separate applications was, that you could not automatically login the user after the signup. But this has been addressed with the introduction of [Auth Token Login](https://github.com/rbCAS/CASino/wiki/Auth-Token-Login).

**Comment by diegobernardes** [comment]
Nevermind, i'm gonna try do the things that i want in a custom authenticator to see if works.

**Comment by esergion** [comment]
@pencil Hi! 
> Devise uses it's own logic to determine if a user is logged in or not. This can lead to inconsistent states (e.g. Devise thinks a user is signed in, CASino does not agree and vice versa)

But, there is devise_cas_authenticatable gem for that, or I missing something..
I'm also want to have all user-logic and CAS in the same app. An central user account management app

**Comment by pencil** [comment]
`devise_cas_authenticatable` doesn't change the fact that Devise uses it's own user session management. In the end the decision is up to you. I just want to make sure that you guys are well aware of the possible downsides of this approach.

**Comment by esergion** [comment]
It's possible to combine, or even use only casino session (since we need only registration, confirmation and other account management features from Devise).
That's what I did in my project.
But those inflections - is pretty shitty stuff

**Comment by tomascharad** [comment]
Hi Sergey,

How did you combine Devise with CASino?

I had to isolate user registration into another app.

2015-06-15 15:27 GMT-03:00 Sergey Pyankov <notifications@github.com>:

> It's possible to combine, or even use only casino session (since we need
> only registration, confirmation and other account management features from
> Devise).
> That's what I did in my project.
> But those inflections - is pretty shitty stuff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rbCAS/CASino/issues/101#issuecomment-112161906>.
>



-- 
Saludos,
Tomás

**Comment by mikel** [comment]
Hey there, I've created a PR #124 to handle this.

**Comment by pencil** [comment]
Will be included in the next release.
