### ISSUE TITLE
How to authenticate webservices?

### ISSUE THREAD

**Issue by diegobernardes** [rbCAS/CASino#107]
There is anyway to authenticate webservices with CASino? Or is better use another solution like oauth/jwt?
Most of the sample i saw is using web apps, redirecting to new pages, etc..

**Comment by pencil** [comment]
Yes, it's recommended to use standards such as OAuth or client certificates to authenticate applications. There has been a [draft for an API](https://wiki.jasig.org/display/CASUM/RESTful+API) but it has been deprecated and support for it was therefore removed in CASino 4.0.

**Comment by pencil** [comment]
Please reopen if you have additional questions.
