### ISSUE TITLE
Customizing routes

### ISSUE THREAD

**Issue by mklemme** [rbCAS/CASino#113]
Whats the easiest way to configure routes? Since this my cas server would be `account.url.com` I wanted to have the root show the users information and such instead of redirecting to sessions.

Whats the best way to configure the routes?

**Comment by pencil** [comment]
Not quite sure if I understood the question correctly. If you want the sessions page to redirect to a custom page, you could add something like this to the top of your `routes.rb` in the application that mounts the CASino engine:

``` ruby
get '/sessions', to: redirect('/swag')
```

Please let me know if that answers your question.
