### ISSUE TITLE
Auto sign in

### ISSUE THREAD

**Issue by Brianpan** [rbCAS/CASino#116]
I'm a newbie in Ruby 
I try using the issue 40 approach
and this is the code
```
##get tickets from cas server
ticket = RestClient("localhost:4000/api/users/tickets")
##auto sign in 
RestClient.post("localhost:4000/login", {:username => "xxx", :password => "123123123", :lt => ticket, :rememberMe => "1"})
```
what should i store in cookies[:tgt]? (a login ticket ticket ? ex: CASino::LoginTicket.create.ticket)
or any approach to use api to get authorize from cas server?

Thanks!

**Comment by luxflux** [comment]
The API has been removed in the 4.0 release. Check [this documentation](https://github.com/rbCAS/CASino/wiki/Auth-Token-Login) to see how to do this with the "Auth Token Login" mechanism.
