### ISSUE TITLE
How to overwrite CASino::SessionsController 

### ISSUE THREAD

**Issue by trkrameshkumar** [rbCAS/CASino#120]
Hi Guys,

I created casino server app from scratch ,and for authorization i am using this ``consul`` gem ( https://github.com/makandra/consul ) according to this gem all controllers need to be given permission or we can skip this authorization by adding  ``skip_power_check`` either way i have to overwrite the ``CASino::SessionsController`` .

**Comment by pencil** [comment]
CASino has it's own session and user handling which is why we do not recommend integrating other gems that could interfere with that. What exactly is your use case? Maybe we can figure out an alternative way that better fits with CASinos architecture.

**Comment by trkrameshkumar** [comment]
Hi @pencil thanks for your reply,
I am trying to integrate ``CASino`` gem in my existing ``rails`` application,which is using  ``consul`` gem for authorization to implement role based access for users,  this ``consul`` gem requires to set permission for all controllers , so when the casino trying to run its ``CASino::SessionsController`` the ``consul`` gem throws permission error.

Can you thing of any such scenario?

**Comment by trkrameshkumar** [comment]
Hey @pencil i fixed this problem by removing the initializr of ``consul`` gem for application controller and applied on whichever controller i want, and guess what now casino working as expected , anyway thanks for your quick response to my question.
