### ISSUE TITLE
How can i access current_user in other controllers 

### ISSUE THREAD

**Issue by trkrameshkumar** [rbCAS/CASino#122]
Hi @pencil 
The ``current_user`` helper method is only available on ``sessions controller`` , other than this session controller i cannot able to access the ``current_user `` helper method on any other controller.

**Comment by calmyournerves** [comment]
Hi Ramesh,
could you give us some more details about what you are trying to accomplish?

**Comment by trkrameshkumar** [comment]
Hi Samuel Sieg (@calmyournerves)

I have 3 rails applications , one of them is a going to be central application for authentication which will be using CASino gem to do that, and other two are  Client applications, I am trying to install casino gem in my existing central rails application instead of using your ready made CASino Server app,  in that case how do i access to the ``current_user`` helper method across all the controlle to perform my operation based on current logged in user.

**Comment by pencil** [comment]
`include CASino::SessionsHelper` in your custom controller.

**Comment by trkrameshkumar** [comment]
Thanks @pencil

**Comment by bakku** [comment]
This did not work for me.

An alternative solution seems to be:

```
class CustomController < ApplicationController
  helper CASino::Engine.helpers

  # custom actions
end
```
