### ISSUE TITLE
How To Login with Rails Applications

### ISSUE THREAD

**Issue by kishoore** [rbCAS/CASino#123]
Hi,
    This is kishore cheruku from India, First of all thank you very much for CASino clear explanation. I successfully install this CASino in my local machine. But my question is i have 3 rails applications , now i would like to take sso for those 3 applications.Am getting confusion for how to configure with CASino and rails applications...

**Comment by pencil** [comment]
Check out [this documentation](http://jasig.github.io/cas/4.0.x/planning/Architecture.html). CASino is your CAS server, you will need a CAS client such as [Rack-CAS](https://github.com/biola/rack-cas) for the Rails applications.
