### ISSUE TITLE
How can I call sign_in from devise?

### ISSUE THREAD

**Issue by andricicezar** [rbCAS/CASino#129]
Hello,

When somebody logins with CASino, I want immediately to sign in him to devise. How can I do that? I found [this](https://github.com/plataformatec/devise/wiki/How-To:-Sign-in-as-another-user-if-you-are-an-admin).

I tried to extend the `casino/session_helper.rb` but I don't know how and how to call devise's method `sign_in`.

Can you help me?

Thank you!

**Comment by ianagne** [comment]
I've had success using the [devise_cas_authenticatable](https://github.com/nbudin/devise_cas_authenticatable) for my casino client apps in the past.

**Comment by luxflux** [comment]
CASino does not support user creation (sign up), only login (sign in). It is not recommended to allow users to sign up with CASino.
Even though, there are some solutions to this. @nicolasiensen explains how he does it in #46.
