### ISSUE TITLE
NameError: uninitialized constant

### ISSUE THREAD

**Issue by henry40408** [rbCAS/CASino#145]
I type `rake casino:service_rule:add['SSO-CLIENT','http://sso-client.dev/']` in the command line and get the following error:

```
rake aborted!
NameError: uninitialized constant CASino::ServiceTicketProcessor::Addressable
/usr/local/lib/ruby/gems/2.2.0/gems/casino-4.0.2/app/processors/casino/service_ticket_processor.rb:30:in `clean_service_url'
/usr/local/lib/ruby/gems/2.2.0/gems/casino-4.0.2/lib/casino/tasks/service_rule.rake:12:in `block (3 levels) in <top (required)>'
-e:1:in `<main>'
Tasks: TOP => casino:service_rule:add
(See full trace by running task with --trace)
```

I use **Ruby on Rails 4.2.5**, **Casino 4.0.2**, and **casino-activerecord_authenticator 4.0.1**.

**Comment by pencil** [comment]
Thanks for the report. Looks like a bug… Probably a missing `require` somewhere.

**Comment by henry40408** [comment]
Should I require anything in any files in my project? I have seen nothing mentioned about requiring anything in documentation.

**Comment by pencil** [comment]
Nope, it's a bug in CASino.

**Comment by nozpheratu** [comment]
I also just ran into this. :+1:
