### ISSUE TITLE
Is there a way to override the default route and controller action?

### ISSUE THREAD

**Issue by allenzhao** [rbCAS/CASino#148]
I might want to add some different view after the user login and make the "/sessions" another path. Is there a way I can do that by not change files in the CASino gem?
And can I modify the controller actions?
Thanks a lot!

**Comment by allenzhao** [comment]
Seems route is a duplicate of #113 , but I think I need to let the user login then redirect to another controller. Is there a simple way to do that? Thanks a lot!

**Comment by pencil** [comment]
`get '/sessions', to: redirect('https://www.google.com')` in `routes.rb` before mounting the CASino engine should do the trick.

**Comment by allenzhao** [comment]
Thanks! That should work!
