### ISSUE TITLE
Link broken on ReadMe

### ISSUE THREAD

**Issue by jfvanderwalt** [rbCAS/CASino#160]
The link on the ReadMe, `CAS 1.0 and CAS 2.0` going to http://jasig.github.io/cas is broken/missing. 

More than happy to fix this and other dead references(across different repos) if you can point me to the right domain.

Cheers

**Comment by calmyournerves** [comment]
Hey there!

It looks like the documentation is now under http://apereo.github.io/cas. Jasig has become part of the Apereo foundation. A PR would be very nice :)
