### ISSUE TITLE
How CAS server identify differency domain name 

### ISSUE THREAD

**Issue by flameA** [rbCAS/CASino#171]
Hi dev CASino team,

This gem so helpful, after setup. My app is work fine. However, i don't know how it work when when can't share cookie, local Storage, session Storage cross a domain. 

Example I have 2 web side with 2 domain is abc.com and xyz.com . I have CAS server have domain like account.abc.com. 
step 1: I sign in to abc.com side, it direct me to account.abc.com 
step 2: i put username and password. server verify true.
step 3: abc.com side: receive server ticket verify true and  make me sign in success in abc.com site.
-----------
when side xyz.com sign in, my server xyz.com automatic verify with account.abc.com server and make me login.
So, problem here. how account.abc.com  identify xyz.com side. what and where info browser save

**Comment by flameA** [comment]
Please help. I take a lot of time for this. and this talk very important.

**Comment by AjayBarot** [comment]
@flameA : You can debug the casino gem to understand the whole process of ticket generation and ticket verification. May be this will help you [sso casino blog](http://blog.codescrum.com/2015/03/31/Single_Sign_On_with_Devise_and_Casino/).

Cheers

**Comment by luxflux** [comment]
I'm not sure if I understood your usecase excatly but it sounds like you want to automatically login a user after a completed sign up in an application independent from CASino.

You may have a look at [Auth-Token-Login](https://github.com/rbCAS/CASino/wiki/Auth-Token-Login), it works for me in several projects like a charm.

**Comment by pencil** [comment]
Not sure why OP went silent [after even pinging me on Twitter](https://twitter.com/flamein_/status/776647424425156608).
