### ISSUE TITLE
How do you deploy on Heroku?

### ISSUE THREAD

**Issue by otherjohn** [rbCAS/CASino#21]
Hi all, can you post instructions on how to deploy on heroku?

**Comment by kyledcline** [comment]
@janncm @DavidLane If `config/cas.yml` and `config/database.yml` are gitignored, how does Heroku know the connection and configuration?

**Comment by DavidLane** [comment]
I'm not sure it'd be possible with out committing config/cas.yml, though I'm happy to be corrected...

**Comment by kyledcline** [comment]
@DavidLane Looks like you're right. So you committed `cas.yml` and it worked off the bat? Thanks. Feel free to share any other problems you ran into with Heroku.

**Comment by DavidLane** [comment]
@kyledcline As far as I can remember, yes. I've not had any problems at all running it on Heroku for what it's worth.
