### ISSUE TITLE
sign_in method for backend sign in

### ISSUE THREAD

**Issue by nicolasiensen** [rbCAS/CASino#46]
I want to sign in users with Casino after they successfully submit the sign up form.

Something like the Devise's [sign_in](http://rubydoc.info/github/plataformatec/devise/master/Devise/Controllers/SignInOut#sign_in-instance_method) method.

Thoughts?

**Comment by nozpheratu** [comment]
For future visitors, here's an up to date example using the ActiveRecord authenticator:

```ruby
class RegistrationsController < Devise::RegistrationsController
  include CASino::SessionsHelper

  private

  def sign_up(resource_name, resource)
    return unless params['service']
    data = { authenticator: 'ActiveRecord', user_data: { username: resource.email }}
    sign_in(data)
  end

  def handle_signed_in_with_service(tgt, options)
    if !service_allowed?(params[:service])
      @service = params[:service]
      render 'casino/sessions/service_not_allowed', status: 403
    else
      @url = acquire_service_ticket(tgt, params[:service], options).service_with_ticket_url
    end
  end

  def after_sign_up_path_for(resource)
    params.has_key?(:service) ? @url : super
  end
end
```

In order for this to work you'll need to ensure the `service` param is forwarded through the registration pipeline (e.g., registration link on the login page and the following registration form tag). I'm sure this example can be improved but it should give you a decent starting point.
