### ISSUE TITLE
API Logout with a service ticket

### ISSUE THREAD

**Issue by gmoore** [rbCAS/CASino#52]
We need to support calling CAS with a service ticket to log the user out. Is there a reason (security or otherwise) that this isn't available in the CASino API? If not, we'll put in a PR for it when we get it together.

**Comment by craigweston** [comment]
I'd like to request this functionality too, as @gmoore's use case is something that I also require for my application.

Although the flaw you have noted regarding the POST failing is valid, my understanding is that this is commonly how single sign out is implemented across applications with CAS:

>CAS is designed to support single sign out: it means that it will be able to invalidate client application sessions in addition to its own SSO session.

>When a CAS session ends, it notifies each of the services that the SSO session is no longer valid, and that relying parties need to invalidate their own session.

>CAS sends an HTTP POST message directly to the service ( back channel communication): this is the traditional way of performing notification to the service.

From: [Logout and Single Logout (SLO)](http://jasig.github.io/cas/development/installation/Logout-Single-Signout.html#single-logout-slo)

Here is some [Additional information] (https://wiki.jasig.org/display/casum/single+sign+out#SingleSignOut-WhereSingleSignOutWorks)

Thank you

**Comment by pencil** [comment]
I think logging out a user based on his username would be a great addition. CASino 4.0 adds support for signed API requests which would help securing this API endpoint. Documentation for is still pending but maybe someone would like to look into this and potentially start working on a PR.

**Comment by pencil** [comment]
The suggested approach is to validate membership status in the individual applications. Single Sign-On requests should not be used since it can't be guaranteed that they are actually delivered successfully.
