### ISSUE TITLE
Support semicolon as URL query separator

### ISSUE THREAD

**Issue by swobspace** [rbCAS/CASino#59]
CASino uses addressable/uri, which does not fully normalize Urls with semicolon like
```
http://server/otrs/index.pl?Action=AgentTicketZoom;TicketID=12345
```
The result after service validation is
```
http://server/otrs/index.pl?Action=AgentTicketZoom%3BTicketID%3D12345
```
which OTRS cannot handle.

More info: https://github.com/sporkmonger/addressable/issues/114 and https://github.com/rbCAS/CASino/issues/58

**Comment by pencil** [comment]
We currently do not have plans to implement this. I'm not even sure if this would have to be fixed in CASino or `addressable`.
