### ISSUE TITLE
Testing CASino

### ISSUE THREAD

**Issue by mongeta** [rbCAS/CASino#68]
Hello,

We're using RUBY CAS Server but after hacking and patching it, we're looking for another solution, and we found CASino.

CASino works well with Ruby 2.x or we need to use 1.9.3 as the .ruby-version says?

We are not able to use LDAP correctly, even it's properly configured in /config/cas.yml

The server has been restarted (CASino) but we can't find any reference in the log files. 

This is on OSX using 10.9.4 and ruby 2.0.0p247

thanks,

**Comment by maungmaung0** [comment]
How to use this for beginner.
