### ISSUE TITLE
JS runtime required

### ISSUE THREAD

**Issue by arthurkarganyan** [rbCAS/CASino#71]
Hello, guys! I have found the when I run 

    bundle exec rails g casino:install

I face with the problem, that there is no JS environment. I have fix this problem with installing therubyracer gem. My proposal is to include this gem into gem dependencies.

Best regards,
Arthur

**Comment by pencil** [comment]
I think it should be up to the user of the CASino engine to chose a JS environment. `CASinoApp` for example (which is the recommended way to setup CASino) depends on `therubyracer`.
