### ISSUE TITLE
Setting locale responsibility

### ISSUE THREAD

**Issue by jandudulski** [rbCAS/CASino#88]
I think that `set_locale` should be removed from this engine since it's not it's responsibility (e.g. move it to `CASinoApp`). In case when I want to allow user to select language on itself I would need to hack the CASino instead of just relying on existing implementation somewhere in my app.

**Comment by pgolm** [comment]
:+1:

**Comment by pencil** [comment]
Thank you for the suggestion. It will be changed in CASino 4.0.
