### ISSUE TITLE
Trying CASino

### ISSUE THREAD

**Issue by ak-uk** [rbCAS/CASino#91]
My environment is the following:
CentOS 7
Apacahe 2.4
Ruby 2.0
MariaDB

I see a CASino login page but logins eventually timeout. 

database.yml looks like this

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: casino
  pool: 5
  username: casuser
  password: password
  socket: /var/lib/mysql/mysql.sock

cas.yml looks like this:

production:
  frontend:
    sso_name: 'CASino'
    footer_text: 'Powered by <a href="http://rbcas.com/">CASino</a>'
  authenticators:

########################################
# LDAP
########################################
    mycompany_ldap:
      authenticator: 'LDAP'
      options:
        host: 'ldap.mycompany.org.uk'
        port: 139
        base: 'ou=people,dc=mycompany,dc=org,dc=uk'
        username_attribute: 'uid'
        #encryption: ''
        admin_user: "uid=casuser,ou=ldapadmin,dc=mycompany,dc=org,dc=uk"
        admin_password: "adminpassword"
        extra_attributes:
          email: 'mail'
          fullname: 'displayname'

########################################
# SQL (ActiveRecord authenticator)
########################################
    my_company_sql_database:
      authenticator: "ActiveRecord"
      options:
        connection:
          adapter: "mysql2"
          host: "localhost"
          username: "casuser"
          password: "password"
          database: "casino"
        table: "users"
        username_column: "username"
        password_column: "password"
        extra_attributes:
          email: "email_database_column"
          fullname: "displayname_database_column"

production.log shows

Started GET "/login" for 10.1.105.205 at 2015-01-27 15:45:14 +0000
Processing by CASino::SessionsController#new as HTML
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/application/_messages.html.erb (0.3ms)
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/application/_footer.html.erb (0.1ms)
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/sessions/new.html.erb within layouts/application (2.8ms)
Completed 200 OK in 25ms (Views: 4.4ms | ActiveRecord: 16.5ms)
Started POST "/login" for 10.1.105.205 at 2015-01-27 15:46:18 +0000
Processing by CASino::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ICBD9rWezceCismqyyJ2PPFMZ387AeCyZOmaP3BykaU=", "lt"=>"LT-14223735148484-sQVQjNoRepCB9Biv6wZY8IVZOfYWlCaWkUrAPDV7", "username"=>"kinga", "password"=>"[FILTERED]", "button"=>""}

Can anyone help?

edit: 

production.log

Processing by CASino::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ICBD9rWezceCismqyyJ2PPFMZ387AeCyZOmaP3BykaU=", "lt"=>"LT-14223762702057-FVQgMypvHLC15Vf96sE9GxAHHgvgqG08H4jSuZnC", "username"=>"kinga", "password"=>"[FILTERED]", "button"=>""}
Login ticket 'LT-14223762702057-FVQgMypvHLC15Vf96sE9GxAHHgvgqG08H4jSuZnC' not found
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/application/_messages.html.erb (0.8ms)
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/application/_footer.html.erb (0.6ms)
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/sessions/new.html.erb within layouts/application (8.2ms)
Completed 403 Forbidden in 56ms (Views: 12.6ms | ActiveRecord: 12.2ms)

edit 2:

with a browser with no plugins...

Processing by CASino::SessionsController#new as HTML
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/application/_messages.html.erb (0.2ms)
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/application/_footer.html.erb (0.1ms)
  Rendered vendor/bundle/ruby/gems/casino-3.0.4/app/views/casino/sessions/new.html.erb within layouts/application (3.0ms)
Completed 200 OK in 25ms (Views: 4.7ms | ActiveRecord: 14.7ms)
Started POST "/login" for 10.1.105.86 at 2015-01-29 16:06:43 +0000
Processing by CASino::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"0XNvikjW0xwBkZZJhJVCZ1489DF+JixMqSuigvcm+88=", "lt"=>"LT-14225475931479-AqLXRmt6z3jaeVPMcyqxgZnFTyPZMJD1R5BJXu1s", "username"=>"kinga", "password"=>"[FILTERED]", "button"=>""}

**Comment by pencil** [comment]
Try logging in through console directly on your server using the command `bundle exec rake casino:authentication:test`.
