### ISSUE TITLE
SAML2

### ISSUE THREAD

**Issue by mike-t** [rbCAS/CASino#94]
Hi guys, great product works really well :+1: 

Any chance of implementing a SAML2 authenticator for CASino as described here: https://wiki.jasig.org/display/CASUM/SAML+Support+in+CAS+4

We are looking to add our Google Apps platform as a consumer of CAS and would to love to see this feature in CASino if possible.

More info on that here: https://developers.google.com/google-apps/sso/saml_reference_implementation

Thanks!

Mike

**Comment by pencil** [comment]
> Any chance of implementing a SAML2 authenticator for CASino

That would be an interesting addition to CASino, but it isn't something we currently have plans to work on. It'd be neat if someone else wanted to implement this and submit a PR, though.

**Comment by pencil** [comment]
I'll close this for now as we don't have any plans to add SAML2 support.

**Comment by johngal-t** [comment]
I'm looking at developing or sponsoring the development of this feature. Any pointers or recommendations on this would be great.

**Comment by pencil** [comment]
* Add controllers and routes required for SAML authentication
* Create a builders similar to `TicketValidationResponseBuilder` to generate SAML responses
* Ensure 100% test coverage
* Manual testing with existing SAML clients

Unfortunately, I currently do not have the time available to build this.

**Comment by pencil** [comment]
Closing since nobody seems to actively pursue this currently.

**Comment by jasonjei** [comment]
I would possibly pursue implementing this with Casino. I'm trying to get Google Apps to work with sportngin/saml_idp

**Comment by ferrisoxide** [comment]
@jasonjei This might give up some help: https://github.com/lawrencepit/ruby-saml-idp

It's old code, but at least roughs out what's required. I'm a bit clueless on SAML, but if you want a hand ping me a message.
