### ISSUE TITLE
Locale (and back_url) as parameters

### ISSUE THREAD

**Issue by ckornaros** [rbCAS/CASino#96]
Hello,
In this CASino's version, the locale is set by the browser language header.
I try to figure out how I can pass the locale as a parameter insted of just looking in the browser language header ?

In the same kind of reflexion, I also need to provide a "back url" parameter to the user so he can go back to the previous url. I did some ugly "hack" and it works but the good ways to do that would be to let the choice to pass some extras parameters like the locale and the back_url.

It's already possible and I miss something ? Can you provide this feature in a future version ? 

Thanks in advance for your help !
PS: Good job for your awsome job :)

**Comment by pencil** [comment]
> I try to figure out how I can pass the locale as a parameter insted of just looking in the browser language header ?

CASino 4.0 will no longer include the logic to determine the language based on the browser language (#88). Instead it now relies on the Rails application setting the locale appropriately. While [CASinoApp will still use the original method](https://github.com/rbCAS/CASinoApp/commit/60a84f196d89d5de0229525fbbffac8e1c1422a7) it's up to you to replace it with what ever suits your use case.

> I also need to provide a "back url" parameter to the user so he can go back to the previous url

Additional parameters can be used in conjunction with [custom views](http://casino.rbcas.com/docs/customization/#views).

**Comment by ckornaros** [comment]
Thanks for your answer @pencil . I forked devise_cas_authenticatable gem and I'm now able to pass all the parameters I needed to CASinoApp :)

**Comment by pencil** [comment]
Good to hear!
