### ISSUE TITLE
is possible use CASino with mongoDB?

### ISSUE THREAD

**Issue by pedrohenriquerls** [rbCAS/CASino#97]

**Comment by luxflux** [comment]
For authentication it would be possible for sure, you just need an authenticator for it. I don't know whether one exists already.

For the internal database structure CASino uses `ActiveRecord::Base` so I don't think you can run it with a MongoDB backend.

**Comment by pedrohenriquerls** [comment]
I working mate found this: https://github.com/digitalnatives/casino-moped_authenticator
I think this solves my problem :) thanks a lot for help
